Tasks complete
GrudinEV/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-14 08:01 UTC by GrudinEV

## Комментарии к Task 8
### 1.	Метод getNames.
Через стримы лаконичней и понятней.
### 2.	Метод getDifferentNames.
Стрим посчитал излишним. Проще собрать список имён, для которых у нас уже есть метод и просто сформировать из него HashSet с уникальными именами.
### 3.	Метод convertPersonToString.
Через стрим проще собрать и читабельней. К тому же в методе, неизвестно зачем, в начало и конец записи добавляется фамилия. Так же посчитал, что это метод для формирования полного имени, которое в дальнейшем используется как «имя» прочими методами.
### 4.	Метод getPersonNames.
Словарь проще собрать через стрим.
### 5.	Метод hasSamePerson.
Тут сделал допущение, что одинаковые персоны это персоны с одинаковыми именем и фамилией. Посчитал так, потому что не зря же мы так яро получаем это полное имя, зачем-то нужны другие методы.
Считаю, что этот метод проще реализовать сразу через стрим
Strim.concat(person1.stream() + person2.stream()).map(this::convertPersonToString).distinct().count() != person1.size() + person2.size();
Но, раз у нас есть метод getDifferentNames, то применил его тут.
### 6.	Метод countEven() 
Понятно, что возвращает количество чётных интов из списка. Не понятно зачем. Как и поле count, которое в нём применяется. Поэтому переписал стрим в одну строку. Может понадобится когда-то 😊 поле count удалил.

2021-12-15 12:58 UTC, genroelgvozo requested changes

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task1.java
> +        return persons.stream().sorted(Comparator.comparing(Person::getId)).collect(Collectors.toList());
так, видимо не понял что требуется (надо было чек сделать чуть другим мне, но не суть)
цитата из описания - нужно их отсортировать в том же порядке, что и переданные id.
а ты сортируешь по возрастанию - а что если я передам List.of(3,1,2) ? у меня должна быть сначала персона 3, потом 1, потом 2

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    }
если у тебя настройки отличаются от того что в файле, на будущее, не жми форматировать файл) (никогда!)
теряется суть ПР, я вижу кучу правок, и только часть из них нужная

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task2.java
> +        return Stream.concat(persons1.stream(), persons2.stream()).sorted(Comparator.comparing(Person::getCreatedAt)).limit(limit).collect(Collectors.toList());
все ок, а че в одну строчку то?)

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task3.java
> +                .collect(Collectors.toList());
все ок

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task4.java
> +        return persons.stream().map(Task4::convert).collect(Collectors.toList());
ок

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task5.java
> +        return persons.stream().map(x -> Task5.convert(x, personAreaIds.get(x.getId()))).collect(Collectors.toList());
в лямбдах не экономьте байтики, пишите person
и опять же, почему водну строчку то? каждый шаг стрима очень удобно переносить

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task6.java
> +                .collect(Collectors.toSet());
получается для каждой арейки у персоны ты бежишь по всем арейкам вообще. О(n*m), а ареек вообще может быть много
можно сделать за O(n+m), с идеей как-то подготовить данные (идея из первой задачи, но там ты не то сделал)

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task7.java
> +    return companies.stream().flatMap(c -> c.getVacancies().stream()).map(Vacancy::getTitle).collect(Collectors.toSet());
все ок, но company и переносы)

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return persons.stream().skip(1).map(person -> getPersonNames(persons).get(person.getId())).collect(Collectors.toList());
ну вот я и не вижу тут никаких комментов, а оказывается они в описании ПР)
кроме лаконичности что было плохого изначально?

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    public String convertPersonToString(Person person) {
ты вроде пишешь через стрим проще, но не вижу стрим)
и да, у тебя короче, но null Олег выглядит странно как полное имя)

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    public String convertPersonToString(Person person) {
а так через стрим есть идея сделать это быстро и красиво (именно то что делалось в самом методе и без багов)

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return persons.stream().collect(Collectors.toMap(Person::getId, this::convertPersonToString));
а если две одинаковые персоны будут?

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return getDifferentNames(newPersons).size() != persons1.size() + persons2.size();
сложная логика, хоть и работает
а stream().anyMatch() + contains у хешсета?
или Collections.disjoint

2021-12-15 12:58 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
все ок, а что было то не так?)

2021-12-17 04:48 UTC, GrudinEV commented on src/tasks/Task8.java
> +        return persons.stream().skip(1).map(person -> getPersonNames(persons).get(person.getId())).collect(Collectors.toList());
Что было плохого изначально:
1. Persons может прилететь null. Тогда в ife бросится NPE.
2. Далее после ifa меняем исходную коллекцию (удаляем первый элемент), чего делать категорически нельзя.
3. Так же посчитал, что под именем подразумевается имя + фамилия. Поэтому "Имя" получаю через метод getPersonNames(). Но, по сравнению с первым вариантом, посчитал, что слишком расточительно для каждого чела формировать новую мапу полных имён по Id. Поэтому инициалировал её до стрима один раз.

2021-12-17 16:58 UTC, GrudinEV commented on src/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
Только могу предположить, что подсчёт велся через общую переменную count, которая могла быть изменена при обращении к методу до этого, а так же другим методом, или через рефлекшн.

2021-12-19 13:48 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
ну она приватная, и во время работы метода нет (ну только если через рефлекшн, да). Но дело в том что стрим может быть параллельным, а операция a+=1 не атомарная

2021-12-19 13:54 UTC, genroelgvozo requested changes

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task1.java
> +        // Ассимптотическая сложность алгоритма O(n*m)
а если все нашлись то это O(n^2) - долго
можно за O(n) - нужно подготовить немного данные

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task1.java
> +        // Ассимптотическая сложность алгоритма O(n*m)
похоже на шестую таску

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task6.java
> +                ).collect(Collectors.toMap(Area::getId, Area::getName));
так, что-то долго, зачем фильтр?
это же каждый раз ты вызываешь values() и бежишь по ним всем, чтобы собрать в сет !!(много памяти)!!
А если это не делать, что-то сломается? (убрать фильтр)

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task6.java
> +                .collect(Collectors.toSet());
сейчас сам алгоритм норм, но подготовка данных странная)

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task6.java
> +                ).collect(Collectors.toMap(Area::getId, Area::getName));
получается по времени O(nm) хоть и ускорил, так еще и n раз сет создаешь и удаляешь (с копированием данных)

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                + (person.getSecondName() == null ? "" : person.getSecondName().trim()));
Stream.of() -> filter(nonNull) -> collector(joining)
а такой код я отказываюсь читать)) (КУЧА ВЛОЖЕННЫХ тернарных операторов, хоть бы вынес в переменные понятные)

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
в хеш сет ты все копируешь, а зачем? есть у toMap третий параметр, о нем было на лекции

2021-12-19 13:54 UTC, genroelgvozo commented on src/tasks/Task8.java
>      @Override
а что hasSamePersons вообще не правил?

2021-12-19 16:12 UTC, GrudinEV commented on src/tasks/Task6.java
> +                .collect(Collectors.toSet());
В подготовке оставляю только те регионы, которые есть в мапе персон и регионов. Складываю их тоже в мапу с id в качестве ключа, чтобы потом быстро забирать нужный регион.
Не догоняю, что не так :)

2021-12-19 16:24 UTC, GrudinEV commented on src/tasks/Task6.java
> +                .collect(Collectors.toSet());
Переделал без отсеивания неактуальных ареек.

2021-12-19 16:26 UTC, GrudinEV commented on src/tasks/Task6.java
> +                ).collect(Collectors.toMap(Area::getId, Area::getName));
Переделал так. Регионы сложил в мапу имя по айди. Отсеивать неактуальные не стал.

2021-12-20 16:37 UTC, genroelgvozo requested changes

2021-12-20 16:37 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                .collect(Collectors.joining(" "));
красиво же?)

2021-12-20 16:37 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                .collect(Collectors.joining(" "));
эта задача как раз показывает, что стримы необязательно юзать только из коллекций. Таких кейсов не очень много, но есть и это показательный пример

2021-12-20 16:37 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return people.size() != persons1Set.size() + persons2Set.size();
ой, а зачем там много сетов?)
ну во-первых если хотел все вместе взять, делаешь allPersons = new HashSet<>(persons1);
и allPersons.addAll(persons2)
а то сет, сет ,стрим, сет...
ну и вообщем-то логика через сайз это уровня олимпиадного кода на C++, в бизнес коде это непонятно

код должен говорить "верну тру если хотя бы одна из персон содержится во втором сете", а не "верну тру, если размеры равны", хоть это в твоем случае и одно и тоже

вот и напиши обычным языком, .stream().anyMatch(set::contains)

2021-12-21 16:51 UTC, genroelgvozo approved these changes

2021-12-22 16:18 UTC, merged